### ISSUE TITLE
Rack 2.x support

### ISSUE THREAD

**Issue by rykov** [dekellum/fishwife#13]
Fishwife cannot be used with recently-released Rails 5 unless it supports Rack 2.x.  Please add this support when you get a chance.  Thank you.

**Comment by dekellum** [comment]
Specs pass using rack 2.0.1 with aa9f434.  I don't find a lot of information on rack 2.x changes, but it seems at least this compatible.  Can @rykov or anyone offer more significant integration testing with this git version, in support of a fishwife 1.9.0 release?

**Comment by rykov** [comment]
Yup - it's kind of tricky to figure out what to look for without a proper changelog:
https://github.com/rack/rack/compare/1.6.4...2.0.0

**Comment by dekellum** [comment]
Released aa9f434 as fishwife 1.9.0.
