### ISSUE TITLE
Configuration of jetty?

### ISSUE THREAD

**Issue by lephyrius** [dekellum/fishwife#14]
I want to configure Jetty to use their own built in gzip compression instead of Rack Deflater. 
How do I do that?

**Comment by dekellum** [comment]
This issue tracker isn't exactly a support forum for Fishwife or Jetty, so I'm going to close this as not-a-bug. 

I think Jetty offers some sort of Servlet Filter for this? You'll need to figure how to set that up embedded, which in Jetty world means setup using java code. Then translate that to jruby's syntax and plug it in by overriding Fishwife::HttpServer (and its RJack::Jetty::ServerFactory parent class) which does the embedded setup.
